default_platform(:ios)

platform :ios do
  desc "Build and distribute the app to Firebase"
  lane :distribute do
    build_app(
      project: "Nomad Journey.xcodeproj", 
      configuration: "Debug",
      scheme: "Nomad Journey",
      export_method: "development",
  		export_options: {
        provisioningProfiles: {
        "com.arrinal.Nomad-Journey" => "manual"
      }
    }
    )
    version = get_version_number(
      xcodeproj: "Nomad Journey.xcodeproj", 
      target: "Nomad Journey"
    )
    build_number = get_build_number(xcodeproj: "Nomad Journey.xcodeproj")
    changelog = File.read("../release-note.txt")
    changelog = changelog.empty? ? "NULL" : changelog
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "tester",
      release_notes: changelog
    )
    build_date = Time.new.getlocal('+07:00').strftime('%Y-%m-%d %H:%M:%S %Z')
    slack(
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      message: "Build #{version} (#{build_number}) has been distributed to Firebase successfully!\n<https://appdistribution.firebase.google.com/testerapps/1:925263839084:ios:ae87973077f40eccedfd49|Download Now>\nChangelog:\n#{changelog}",
      success: true,
      payload: { 
        "Build Date" => build_date,
        "Built by" => `git log --format='%an' -n 1`.strip
      },
      attachment_properties: {
      fallback: "Build information",
      color: "#36a64f",
      pretext: "Firebase Build"
  }
    )

  end
end
