default_platform(:ios)

platform :ios do
  desc "Build and distribute the app to Firebase"
  lane :distribute do
    build_app(
      project: "Nomad Journey.xcodeproj", 
      configuration: "Debug",
      scheme: "Nomad Journey",
      export_method: "development",
  		export_options: {
        provisioningProfiles: {
        "com.arrinal.Nomad-Journey" => "manual"
      }
    }
    )
    version = get_version_number(
      xcodeproj: "Nomad Journey.xcodeproj", 
      target: "Nomad Journey"
    )
    build_number = get_build_number(xcodeproj: "Nomad Journey.xcodeproj")
    changelog = File.read("../release-note.txt")
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "tester",
      release_notes: changelog
    )
    slack(
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      message: "Build #{version} (#{build_number}) has been distributed to Firebase successfully!\nChangelog:\n#{changelog}",
      success: true,
      payload: { 
        "Build Date" => Time.new.to_s,
        "Built by" => `git log --format='%an' -n 1`.strip
      },
      attachments: [{
          "fallback" => "You can download the build on Firebase here.",
          "text" => "<https://appdistribution.firebase.google.com/testerapps/1:925263839084:ios:ae87973077f40eccedfd49|Click here to download the build on Firebase>",
          "color" => "#36a64f",
          "pretext" => "Firebase Build"
      }]
    )

  end
end
