name: Ngetes Aja

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  build_and_distribute:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Environment Variable BAJIGUR
        run: echo "Nilai BAJIGUR adalah ${{ vars.BAJIGUR }} | ${{ secrets.FAD_LINK }}
