name: Ngetes Aja

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Environment Variable ADUH
        run: echo "Nilai ADUH adalah $ADUH"
