name: iOS Distribute

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  build_and_distribute:
    runs-on: macos-latest
    # environment: test
    steps:
      - name: Print before
        run: echo "Nilai before adalah ${{ env.ADUH }}"
      - name: Modify Environment Variable
        run: echo "ADUH=ubah" >> $GITHUB_ENV

      - name: Print after
        run: echo "Nilai ADUH yang diubah adalah ${{ env.ADUH }}"
