name: iOS Distribute

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest
    # environment: test
    environment: 
      name: test
    steps:
      - name: Print Environment Variable ADUH
        run: echo "Nilai ADUH adalah ${{ env.ADUH }}"
