name: Ngetes Aja

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
      releaseNotes:
        description: Release Notes

jobs:
  build_and_distribute:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Environment Variable BAJIGUR
        run: echo "Nilai BAJIGUR adalah ${{ vars.BAJIGUR }}"
      - name: Update release notes
        run: echo "${{ github.event.inputs.releaseNotes }}" | sed 's/\\n/ /g' > release-note.txt
      - name: Print release notes
        run: cat release-note.txt
      - name: update var
        run: |
            gh variable list
            gh variable set BAJIGUR --body "Set from workflow"
            gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AING }}
      - name: Print terbaru Variable BAJIGUR
        run: echo "Nilai BAJIGUR adalah ${{ vars.BAJIGUR }}"
